#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: glusterrestd

. /etc/rc.subr

name="glusterrestd"
rcvar=`set_rcvar`
command=/usr/bin/gunicorn
pidfile="/var/run/${name}.pid"
glusterrestd_flags="-D -c /etc/glusterrest/gunicorn_config.py glusterrest.main:app --pid /var/run/${name}.pid"
start_cmd="$command ${glusterrestd_flags}"

load_rc_config $name
run_rc_command "$1"
